apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: prometheus-demo
    monitoring: device-mapper
  name: prometheus-demo
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prometheus-demo
      monitoring: device-mapper
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: prometheus-demo
        monitoring: device-mapper
    spec:
      containers:
      - image: gcr.io/inspired-bus-194216/springboot-prometheus
        name: prometheus-demo
        ports:
        - containerPort: 8080
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    monitoring: device-mapper
    run: prometheus-demo
  name: prometheus-demo
  namespace: platform
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    monitoring: device-mapper
    run: prometheus-demo
  type: ClusterIP
status:
  loadBalancer: {}